'use client';

import {useCallback,useEffect,useState,type ReactNode} from 'react';
import s from './CompetitionWorkbench.module.css';

type Row=Record<string,any>;
type Panel='overview'|'research'|'backtest'|'policy'|'execution'|'review'|'evidence';
const sections:[Panel,string,string][]=[['overview','Mission control','01'],['research','Research & sources','02'],
  ['backtest','Strategy & replay','03'],['policy','Signed policy','04'],['execution','Execution & safety','05'],
  ['review','Review workflow','06'],['evidence','Evidence room','07']];
const short=(value:string|undefined)=>value?`${value.slice(0,10)}…${value.slice(-8)}`:'Not recorded';
const fmt=(value:number|null|undefined,digits=2)=>value==null?'—':Number(value).toLocaleString('en-US',{minimumFractionDigits:digits,maximumFractionDigits:digits});
const pct=(value:number|null|undefined)=>value==null?'—':`${value>=0?'+':''}${fmt(value)}%`;
const date=(value:string|number|undefined)=>value?new Date(typeof value==='number'?value*1000:value).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}):'—';
const units=(raw:string|undefined,decimals:number,digits=4)=>{
  if(!raw)return '—';
  const value=BigInt(raw),base=10n**BigInt(decimals),whole=value/base,fraction=(value%base).toString().padStart(decimals,'0').slice(0,digits);
  return `${whole.toString()}.${fraction.padEnd(digits,'0')}`;
};

function Icon({name,size=20}:{name:string,size?:number}) {
  const paths:Record<string,ReactNode>={
    arrow:<><path d="M4 12h16M14 6l6 6-6 6"/></>,
    check:<path d="m5 12 4 4L19 6"/>,
    shield:<><path d="M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6l-8-3Z"/><path d="m8 12 3 3 5-6"/></>,
    chart:<><path d="M3 4v16h18"/><path d="m6 14 5-5 4 3 5-7"/></>,
    link:<><path d="m10 14 4-4M8 16l-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0M16 8l1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0" transform="translate(1 0) scale(.9)"/></>,
    play:<path d="m8 4 12 8-12 8V4Z"/>,
    file:<><path d="M5 3h10l4 4v14H5V3Z"/><path d="M14 3v5h5M8 12h8M8 16h6"/></>,
    plus:<path d="M12 4v16M4 12h16"/>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.file}</svg>;
}
function Badge({children,tone='muted'}:{children:ReactNode,tone?:string}){
  return <span className={`${s.badge} ${s[tone]||''}`}><i/>{children}</span>;
}
function Empty({title,children}:{title:string,children:ReactNode}){
  return <div className={s.empty}><Icon name="file" size={30}/><h3>{title}</h3><p>{children}</p></div>;
}
function Stat({label,value,note,tone}:{label:string,value:string,note:string,tone?:string}){
  return <div className={s.stat}><span>{label}</span><strong className={tone?s[tone]:''}>{value}</strong><small>{note}</small></div>;
}
function Hash({label,value}:{label:string,value?:string}){
  return <div className={s.hash}><span>{label}</span><code title={value}>{value||'Not recorded'}</code></div>;
}
function Curve({series,benchmark,price=false}:{series:[number,number][],benchmark?:[number,number][],price?:boolean}) {
  const W=920,H=270,L=60,R=16,T=22,B=35;
  const numbers=[...series,...(benchmark||[])].map(p=>p[1]);
  let min=Math.min(...numbers),max=Math.max(...numbers);
  const pad=Math.max((max-min)*.15,max*.002);min-=pad;max+=pad;
  const first=series[0]?.[0]||0,last=series.at(-1)?.[0]||1;
  const x=(ts:number)=>L+(ts-first)/Math.max(1,last-first)*(W-L-R);
  const y=(v:number)=>T+(max-v)/Math.max(.001,max-min)*(H-T-B);
  const path=(points:[number,number][])=>points.map((p,i)=>`${i?'L':'M'}${x(p[0]).toFixed(1)},${y(p[1]).toFixed(1)}`).join(' ');
  const d=path(series),base=H-B;
  return <svg className={s.curve} viewBox={`0 0 ${W} ${H}`} role="img" aria-label={price?'AVAX historical closing price':'Actual historical strategy and buy-and-hold equity'}>
    <defs><linearGradient id="avaxCurveFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#b48bff" stopOpacity=".21"/><stop offset="100%" stopColor="#b48bff" stopOpacity="0"/></linearGradient></defs>
    {[0,1,2,3,4].map(i=>{const v=min+(max-min)*i/4;return <g key={i}><line x1={L} x2={W-R} y1={y(v)} y2={y(v)} stroke="currentColor" opacity=".1"/><text x={L-12} y={y(v)+4} textAnchor="end">{price?`$${fmt(v,1)}`:`${fmt(v/1000,1)}k`}</text></g>;})}
    <path d={`${d} L${x(last)},${base} L${x(first)},${base}Z`} fill="url(#avaxCurveFill)"/>
    {benchmark?.length?<path d={path(benchmark)} fill="none" stroke="#8290aa" strokeWidth="2" strokeDasharray="5 5"/>:null}
    <path d={d} fill="none" stroke="#bca0ff" strokeWidth="2.6" strokeLinejoin="round"/>
    {series.length?<circle cx={x(last)} cy={y(series.at(-1)![1])} r="4" fill="#bca0ff"/>:null}
    {[0,.25,.5,.75,1].map(f=><text key={f} x={x(first+(last-first)*f)} y={H-10} textAnchor={f===0?'start':f===1?'end':'middle'}>{new Date((first+(last-first)*f)*1000).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})}</text>)}
  </svg>;
}

export default function CompetitionWorkbench() {
  const [state,setState]=useState<Row|null>(null);
  const [fujiWallet,setFujiWallet]=useState<Row|null>(null);
  const [fujiExecution,setFujiExecution]=useState<Row|null>(null);
  const [panel,setPanel]=useState<Panel>('overview');
  const [loading,setLoading]=useState<string|null>(null);
  const [error,setError]=useState<string|null>(null);
  const [showRaw,setShowRaw]=useState(false);
  const refresh=useCallback(async()=>{
    const response=await fetch('/api/competition/state',{cache:'no-store'});
    const value=await response.json();
    if(!response.ok)throw new Error(value.error||'Competition service unavailable');
    setState(value);
  },[]);
  const refreshFujiWallet=useCallback(async()=>{
    const response=await fetch('/api/competition/fuji/wallet',{cache:'no-store'});const value=await response.json();
    if(response.ok)setFujiWallet(value);
  },[]);
  const refreshFujiExecution=useCallback(async()=>{
    const response=await fetch('/api/competition/fuji/execution',{cache:'no-store'});const value=await response.json();
    if(response.ok)setFujiExecution(value);
  },[]);
  useEffect(()=>{let active=true;refresh().catch(e=>active&&setError(e.message));refreshFujiWallet().catch(()=>undefined);refreshFujiExecution().catch(()=>undefined);
    const timer=setInterval(()=>{refresh().catch(()=>undefined);refreshFujiWallet().catch(()=>undefined);refreshFujiExecution().catch(()=>undefined);},3000);return()=>{active=false;clearInterval(timer);};},[refresh,refreshFujiWallet,refreshFujiExecution]);
  const act=async(action:string,target:Panel)=>{
    setLoading(action);setError(null);setPanel(target);
    try{
      const response=await fetch(`/api/competition/${action}`,{method:'POST',headers:{'content-type':'application/json','x-nerya-competition':'avalanche'},body:'{}'});
      const value=await response.json();if(value.state)setState(value.state);
      if(!response.ok)throw new Error(value.error||'Operation could not complete');
      setState(value);
    }catch(e){setError(e instanceof Error?e.message:'Operation could not complete');}
    finally{setLoading(null);}
  };
  const download=async()=>{
    try{const response=await fetch('/api/competition/bundle');if(!response.ok)throw new Error('Evidence export unavailable');
      const bundle=await response.json();const object=URL.createObjectURL(new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'}));
      const a=document.createElement('a');a.href=object;a.download=`nerya-avalanche-${state?.runId||'evidence'}.json`;a.click();URL.revokeObjectURL(object);
    }catch(e){setError(e instanceof Error?e.message:'Export failed');}
  };
  const busy=!!loading||!!state?.busy;
  const m=state?.market,bt=state?.backtest,p=state?.policy,execution=state?.execution,attack=state?.attack,review=state?.review;
  const metrics=bt?.metrics;
  const completed=[m,bt,p,execution,review].filter(Boolean).length;
  const next: [string,Panel,string] = !m?['research','research','Capture live research']:!bt?['backtest','backtest','Run historical replay']:!p?['policy','policy','Authorize local test policy']:!execution?['execute','execution','Execute local rehearsal']:!attack?['attack','execution','Test the spending boundary']:!review?['review','review','Build the review plan']:['','evidence','Inspect the evidence'];
  const button=(action:string,target:Panel,label:string,secondary=false)=><button className={secondary?s.secondary:s.primary} onClick={()=>void act(action,target)} disabled={busy} data-action={action}>{loading===action?<span className={s.spinner}/>:<Icon name={secondary?'shield':'arrow'} size={17}/>} {loading===action?'Working…':label}</button>;

  return <div className={s.workbench} data-testid="competition-workbench">
    <aside className={s.sidebar}>
      <a className={s.brand} href="/competition/avalanche"><img src="/branding/Logo.png" alt=""/><span>Nerya<span className={s.brandDot}>.</span></span></a>
      <div className={s.edition}><span className={s.avaxMark}>▲</span><div>Avalanche edition<small>COMPETITION WORKTREE</small></div></div>
      <div className={s.navLabel}>YOUR WORKSPACE</div>
      <nav aria-label="Competition workflow">{sections.map(([id,label,number])=><button key={id} onClick={()=>setPanel(id)} className={panel===id?s.navActive:''} data-panel={id}><span>{number}</span>{label}{(id==='research'&&m||id==='backtest'&&bt||id==='policy'&&p||id==='execution'&&execution||id==='review'&&review)?<i/>:null}</button>)}</nav>
      <div className={s.sideBottom}><div className={s.isolated}><Icon name="shield"/><div>Isolated by design<small>main / gwdc untouched</small></div></div><p>Separate branch, ports and runtime.<br/>No production accounts loaded.</p><code>competition/avalanche-2026</code></div>
    </aside>
    <div className={s.workspace}>
      <header className={s.topbar}><div><span className={s.crumb}>COMPETITION</span><span className={s.slash}>/</span><span>{sections.find(x=>x[0]===panel)?.[1]}</span></div><div className={s.topActions}><Badge tone={fujiExecution?.status==='confirmed'?'success':fujiWallet&&BigInt(fujiWallet.balances.owner.native)>0n?'success':state?.fuji?.status==='verified'?'success':'muted'}>{fujiExecution?.status==='confirmed'?'Fuji · execution confirmed':fujiWallet&&BigInt(fujiWallet.balances.owner.native)>0n?'Fuji · wallet funded':'Fuji · read only'}</Badge><Badge tone="warning">Local EVM · safety test</Badge><button onClick={()=>void download()} className={s.iconButton} title="Export full evidence bundle" aria-label="Export full evidence bundle"><Icon name="file"/></button></div></header>
      <div className={s.disclosure}><span>PROOF MODE</span> Public market data + a real Avalanche Fuji testnet PolicyVault execution. The oversized-order rejection remains an isolated local safety test. <strong>Testnet assets only.</strong></div>
      <div className={s.content}>
        {error?<div role="alert" className={s.error}><strong>Operation needs attention</strong><p>{error}</p></div>:null}
        <div className={s.pageHeading}><div><div className={s.eyebrow}>NERYA / AUTONOMOUS FINANCE</div><h1>{panel==='overview'?'Autonomy, within your limits.':panel==='research'?'Start with evidence.':panel==='backtest'?'A strategy you can inspect.':panel==='policy'?'The agent gets a boundary.':panel==='execution'?'Trust the receipt, not the claim.':panel==='review'?'Learn without widening authority.':'Every action leaves a trace.'}</h1><p>{panel==='overview'?'One bounded journey from research to a verifiable execution.':panel==='research'?'Real source records. Closed candles. Explicit coverage and chain identity.':panel==='backtest'?'The original Nerya replay engine, with next-bar fills and visible assumptions.':panel==='policy'?'A typed owner authorization, enforced by the contract—not a promise in a prompt.':panel==='execution'?'A successful trade and an intentionally rejected one. Both are observable.':panel==='review'?'A separate review workflow, bound to this strategy, policy and execution.':'Inspect the original bundle, its content hashes and the execution event.'}</p></div><span className={s.progressCount}><b>{completed}</b><span>/ 5<br/>milestones</span></span></div>

        {panel==='overview'&&<>
          <section className={s.mission}><div className={s.missionTop}><Badge tone="brandTone">AVAX / POLICY-BOUNDED STRATEGY</Badge><span>REFERENCE SCRIPT · NOT AN LLM RUN</span></div><h2>Research. Replay.<br/>Authorize. Verify.</h2><p>Research AVAX using public market data. Replay a transparent trend strategy. Rehearse an execution with a signed spending policy—and prove that an oversized order cannot pass.</p><div className={s.missionBottom}>{next[0]?button(next[0],next[1],next[2]):<button className={s.primary} onClick={()=>setPanel('evidence')}>Inspect the evidence <Icon name="arrow"/></button>}<span>No production keys · No hidden trades</span></div><div className={s.missionOrb} aria-hidden="true"><div/><div/><div/><b>N</b></div></section>
          <div className={s.journey}>{[['01','Research','Live history + Fuji RPC',!!m],['02','Replay','Nerya original engine',!!bt],['03','Authorize','EIP-712 signed policy',!!p||!!fujiExecution?.policy],['04','Execute',fujiExecution?.status==='confirmed'?'Fuji public receipt':'Local contract receipt',!!execution||fujiExecution?.status==='confirmed'],['05','Review','Separate two-node plan',!!review]].map(([n,title,copy,done],i)=><div key={String(n)} className={done?s.journeyDone:''}><span>{done?<Icon name="check" size={16}/>:n}</span><h3>{title}</h3><p>{copy}</p>{i<4?<i>→</i>:null}</div>)}</div>
          <div className={s.twoCol}><section className={s.card}><div className={s.cardTitle}><Icon name="shield"/><h3>Freedom has an explicit budget.</h3></div><div className={s.budgetGrid}><div><small>PER TRADE</small><strong>10 <span>test USDC</span></strong></div><div><small>PER UTC DAY</small><strong>30 <span>test USDC</span></strong></div><div><small>POLICY TOTAL</small><strong>50 <span>test USDC</span></strong></div></div><p className={s.note}>Owner-signed input-token budgets. Testnet only—not a dollar-price oracle.</p></section><section className={s.card}><div className={s.cardTitle}><Icon name="link"/><h3>Avalanche integration, precisely stated.</h3></div><div className={s.checkRow}><span>Fuji RPC + LFJ deployment reads</span><Badge tone={state?.fuji?.status==='verified'?'success':'muted'}>{state?.fuji?.status==='verified'?'Verified':'Not fetched'}</Badge></div><div className={s.checkRow}><span>Dedicated Fuji owner wallet</span><Badge tone={fujiWallet&&BigInt(fujiWallet.balances.owner.native)>0n?'success':'muted'}>{fujiWallet?`${units(fujiWallet.balances.owner.native,18,4)} test AVAX`:'Checking…'}</Badge></div><div className={s.checkRow}><span>Fuji PolicyVault + public LFJ swap</span><Badge tone={fujiExecution?.status==='confirmed'?'success':'warning'}>{fujiExecution?.status==='confirmed'?'Confirmed':'Not broadcast'}</Badge></div><div className={s.checkRow}><span>Local oversized-order safety test</span><Badge tone={attack?'success':'muted'}>{attack?'Verified':'Available'}</Badge></div></section></div>
        </>}

        {panel==='research'&&(!m?<section className={s.card}><Empty title="Capture the underlying facts first.">No prefilled prices or invented activity. The research step fetches public AVAX candles and independently checks the Fuji chain and LFJ contracts.</Empty><div className={s.centerAction}>{button('research','research','Capture live research')}</div></section>:<>
          <div className={s.stats}><Stat label="Latest completed close" value={`$${fmt(m.lastClose)}`} note={m.pair}/><Stat label="Daily candles" value={String(m.closedBars)} note="Completed bars only"/><Stat label="Source" value={m.source.includes('Coinbase')?'Coinbase':'Binance'} note="Public historical data"/><Stat label="Fuji block" value={state?.fuji?.blockNumber?Number(state.fuji.blockNumber).toLocaleString():'Unavailable'} note="Read-only chain verification"/></div>
          <section className={s.card}><div className={s.cardTitle}><div><h3>AVAX / historical price</h3><p>{date(m.start)} — {date(m.end)} · 1D</p></div><Badge tone="success">Real source data</Badge></div><Curve series={m.candles.map((r:Row)=>[r.ts,r.close])} price/><p className={s.note}>{m.limitations}</p></section>
          <div className={s.twoCol}><section className={s.card}><div className={s.cardTitle}><h3>Avalanche Fuji / LFJ</h3><Badge tone={fujiExecution?.status==='confirmed'?'success':state?.fuji?.status==='verified'?'success':'warning'}>{fujiExecution?.status==='confirmed'?'Public execution confirmed':state?.fuji?.status||'Pending'}</Badge></div>{state?.fuji?.status==='verified'?<><Hash label="Router" value={state.fuji.router}/><Hash label="Observed Fuji block" value={state.fuji.blockHash}/>{fujiWallet?<><Hash label="Dedicated Fuji owner" value={fujiWallet.addresses.owner}/><div className={s.checkRow}><span>Public test AVAX balance</span><strong>{units(fujiWallet.balances.owner.native,18,4)} AVAX</strong></div><div className={s.checkRow}><span>LFJ test USDC balance</span><strong>{units(fujiWallet.balances.owner.usdc,6,4)} USDC</strong></div></>:null}{fujiExecution?.status==='confirmed'?<><Hash label="Public Fuji PolicyVault" value={fujiExecution.vault}/><Hash label="Public swap transaction" value={fujiExecution.executionEvidence?.transactionHash}/><div className={s.checkRow}><span>Executed route</span><strong>LFJ V2.1 · {fujiExecution.executionEvidence?.binStep} bps</strong></div></>:null}<p className={s.note}>LFJ-specific test USDC; testnet assets only. Wallet balances and the confirmed transaction are read from public Avalanche Fuji.</p></>:<p className={s.note}>{state?.fuji?.reason||'Fuji validation has not completed.'}</p>}</section><section className={s.card}><h3>Source integrity</h3><Hash label="Historical data digest" value={m.dataHash}/><div className={s.checkRow}><span>Closed candles only</span><Icon name="check"/></div><div className={s.checkRow}><span>Synthetic fallback</span><strong>Disabled</strong></div><div className={s.checkRow}><span>Retrieved</span><span>{new Date(m.downloadedAt).toLocaleString('en-US',{timeZone:'UTC'})} UTC</span></div><a className={s.textLink} href={m.sourceUrl} target="_blank" rel="noreferrer">Open original market source ↗</a></section></div><div className={s.footerAction}>{!bt?button('backtest','backtest','Run historical replay'):<button className={s.primary} onClick={()=>setPanel('backtest')}>View replay <Icon name="arrow"/></button>}</div>
        </>)}

        {panel==='backtest'&&(!bt?<section className={s.card}><Empty title={m?'Replay the reference strategy.':'Research is required before a replay.'}>The run uses Nerya’s existing Python engine. Performance is computed from downloaded candles, with costs and later-bar execution.</Empty>{m?<div className={s.centerAction}>{button('backtest','backtest','Run historical replay')}</div>:null}</section>:<>
          <div className={s.stats}><Stat label="Strategy return" value={pct(metrics.total_return_pct)} tone={metrics.total_return_pct>=0?'positive':'negative'} note="Historical replay · not live P&L"/><Stat label="Buy & hold" value={pct(metrics.benchmark_buy_hold_return_pct)} note="Same evaluation window"/><Stat label="Maximum drawdown" value={`${fmt(metrics.max_drawdown_pct)}%`} note="Historical peak-to-trough"/><Stat label="Recorded fills" value={String(bt.trades.length)} note="Includes terminal accounting fills"/></div>
          <section className={s.card}><div className={s.cardTitle}><div><h3>AVAX Trend / Risk Budget <span className={s.version}>v1</span></h3><p>{date(metrics.start_utc)} — {date(metrics.end_utc)} · 85% NAV allocation · long / cash</p></div><Badge tone="success">Replay completed</Badge></div><div className={s.legend}><span><i/>Strategy</span><span><i className={s.benchmarkDot}/>Buy & hold</span><small>Initial capital: $10,000 · replay only</small></div><Curve series={bt.equity} benchmark={bt.benchmark}/><div className={s.chartChecks}><span><Icon name="check" size={15}/>Next-bar signal fills checked</span><span>30 bps fees / leg</span><span>10 bps modeled slippage / leg</span><span>30-bar warm-up excluded</span></div></section>
          <section className={s.card}><div className={s.cardTitle}><h3>Strategy workflow</h3><Badge>Inspectable reference script</Badge></div><div className={s.workflow}><div><small>OBSERVE</small><strong>Closed AVAX candle</strong><p>1D historical prefix</p></div><i>→</i><div><small>DECIDE</small><strong>10 / 30 day regime</strong><p>Fast &gt; slow + price &gt; slow</p></div><i>→</i><div><small>SIZE</small><strong>85% of NAV</strong><p>15% reserve</p></div><i>→</i><div><small>FILL</small><strong>Next bar open</strong><p>Costs included</p></div></div><p className={s.note}>Weak or negative performance remains a completed replay. These CEX price histories do not model LFJ bins, pool depth or gas. Engine-generated terminal closes are separate accounting fills.</p></section>
          <section className={s.card}><div className={s.cardTitle}><h3>Execution records</h3><span className={s.note}>Latest 5 historical fills</span></div><div className={s.tableWrap}><table><thead><tr><th>Filled at (UTC)</th><th>Side</th><th>Price</th><th>Quantity</th><th>Notional</th><th>Fee</th></tr></thead><tbody>{bt.trades.slice(-5).map((t:Row,i:number)=><tr key={i}><td>{date(t.ts)}</td><td><span className={t.side==='buy'?s.buy:s.sell}>{t.engine_generated ? "FINAL CLOSE" : t.side.toUpperCase()}</span></td><td>${fmt(t.price)}</td><td>{fmt(t.qty,4)}</td><td>${fmt(t.notional)}</td><td>${fmt(t.fee)}</td></tr>)}</tbody></table></div></section><div className={s.footerAction}>{!p?button('policy','policy','Authorize local test policy'):<button className={s.primary} onClick={()=>setPanel('policy')}>View signed policy <Icon name="arrow"/></button>}</div>
        </>)}

        {panel==='policy'&&<>
          <div className={s.policyHero}><div className={s.policyShield}><Icon name="shield" size={42}/></div><div><Badge tone={p?'success':'warning'}>{p?'Signature verified / local owner':'Local test authorization'}</Badge><h2>The model cannot rewrite<br/>the spending limit.</h2><p>The owner signs structured policy fields. The vault validates the signer, scope, expiry and budgets on every execution.</p></div></div>
          <div className={s.twoCol}><section className={s.card}><div className={s.cardTitle}><h3>Delegated trading authority</h3><Badge tone={fujiExecution?.policy?'success':'warning'}>{fujiExecution?.policy?'FUJI / EIP-712':'LOCAL TEST'}</Badge></div><div className={s.policyFields}>{(fujiExecution?.policy?[['Chain','Avalanche Fuji / 43113'],['Input → output','LFJ test USDC → WAVAX'],['Per trade cap','10 test USDC'],['Daily spend cap','30 test USDC / UTC day'],['Lifetime policy cap','50 test USDC'],['Recipient','PolicyVault only'],['Route',`LFJ V2.1 / ${fujiExecution.policy.policy.binStep} bps`],['Delegated agent',short(fujiExecution.agent)]]:[['Chain','Local EVM / 31337'],['Input → output','tUSDC → tWAVAX'],['Per trade cap','10 tUSDC'],['Daily spend cap','30 tUSDC / UTC day'],['Lifetime policy cap','50 tUSDC'],['Recipient','Vault only'],['Route','Fixed one-hop LFJ ABI fixture']]).map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section><section className={s.card}><h3>What is actually enforced</h3><div className={s.guardList}>{['Owner EIP-712 signature','Chain + verifying-contract binding','Agent identity + exact token route','Single / daily / total input-token caps','Replay protection + revocation','Signed output-rate floor','Exact allowance, cleared after swap','Actual token balance-delta validation'].map(item=><div key={item}><Icon name="check" size={16}/>{item}</div>)}</div><div className={s.callout}><strong>A price floor is not a price oracle.</strong><p>This prototype does not claim to enforce portfolio drawdown on-chain. The public Fuji transaction uses testnet assets and the contract is not audited.</p></div></section></div>
          {fujiExecution?.policy?<section className={s.card}><div className={s.cardTitle}><h3>Public Fuji authorization receipt</h3><Badge tone="success">Activated on Fuji</Badge></div><Hash label="Policy digest" value={fujiExecution.policy.policyHash}/><Hash label="PolicyVault" value={fujiExecution.vault}/><Hash label="Delegated agent" value={fujiExecution.agent}/><Hash label="Activation transaction" value={fujiExecution.transactions?.find((x:Row)=>x.name==='activate_policy')?.hash}/><p className={s.note}>Dedicated testnet owner and agent accounts only. No production wallet or mainnet funds were used.</p></section>:null}
          {p?<section className={s.card}><div className={s.cardTitle}><h3>Authorization receipt</h3><Badge tone="success">Activated</Badge></div><Hash label="Policy digest" value={p.policyHash}/><Hash label="Verifying contract" value={p.domain.verifyingContract}/><Hash label="Delegated agent" value={p.policy.agent}/><Hash label="Local authorization transaction" value={p.transactionHash}/><p className={s.note}>The signing account is ephemeral and local to this rehearsal. No production wallet was accessed.</p></section>:null}
          <div className={s.footerAction}>{!p?(bt?button('policy','policy','Authorize local test policy'):null):!execution?button('execute','execution','Execute 10 tUSDC rehearsal'):<button className={s.primary} onClick={()=>setPanel('execution')}>Inspect execution <Icon name="arrow"/></button>}</div>
        </>}

        {panel==='execution'&&(!execution&&!fujiExecution?<section className={s.card}><Empty title={p?'Execute one bounded test intent.':'Authorize a policy before execution.'}>The rehearsal uses a real historical BUY decision. The public Fuji proof, when available, is shown separately from the local safety test.</Empty>{p?<div className={s.centerAction}>{button('execute','execution','Execute 10 tUSDC rehearsal')}</div>:null}</section>:<>
          {fujiExecution?.status==='confirmed'?<><section className={s.executionHero}><div><Badge tone="success">Confirmed / Avalanche Fuji</Badge><h2>{fujiExecution.executionEvidence.amountIn} <span>test USDC</span><i>→</i>{fmt(Number(fujiExecution.executionEvidence.amountOut),6)} <span>WAVAX</span></h2><p>Public testnet transaction · delegated agent · policy-constrained LFJ V2.1 swap</p></div><div className={s.seal}><Icon name="check" size={30}/><span>FUJI<br/>CONFIRMED</span></div></section><div className={s.twoCol}><section className={s.card}><div className={s.cardTitle}><h3>Public execution receipt</h3><Badge tone="success">Status 1</Badge></div><Hash label="Fuji transaction" value={fujiExecution.executionEvidence.transactionHash}/><Hash label="PolicyVault" value={fujiExecution.vault}/><Hash label="Intent hash" value={fujiExecution.executionEvidence.intentHash}/><div className={s.checkRow}><span>Block</span><strong>{Number(fujiExecution.executionEvidence.blockNumber).toLocaleString()}</strong></div><div className={s.checkRow}><span>LFJ route</span><strong>V2.1 / {fujiExecution.executionEvidence.binStep} bps</strong></div><div className={s.checkRow}><span>Router allowance after swap</span><strong>{String(fujiExecution.executionEvidence.routerAllowance)}</strong></div><a className={s.textLink} href={fujiExecution.executionEvidence.explorerUrl} target="_blank" rel="noreferrer">Open public Snowtrace receipt ↗</a></section><section className={s.card}><h3>Evidence committed on Fuji</h3><Hash label="Evidence digest" value={fujiExecution.executionEvidence.evidenceHash}/><Hash label="Policy digest" value={fujiExecution.policy?.policyHash}/><div className={s.guardList}>{['Caller is the delegated agent','Input is within the signed cap','Exact Fuji token route is policy-bound','Recipient is the PolicyVault','Output clears the signed rate floor','Router allowance returns to zero'].map(item=><div key={item}><Icon name="check" size={16}/>{item}</div>)}</div><p className={s.note}>This is a real public Avalanche Fuji testnet transaction. It is not mainnet trading and does not prove profitability.</p></section></div></>:null}
          {execution?<>
          <section className={s.executionHero}><div><Badge tone="success">Confirmed / local EVM</Badge><h2>10 <span>tUSDC</span><i>→</i>{fmt(Number(execution.amountOut),6)} <span>tWAVAX</span></h2><p>Actual contract execution · historical-intent rehearsal · no real funds</p></div><div className={s.seal}><Icon name="check" size={30}/><span>EVIDENCE<br/>MATCHED</span></div></section>
          <div className={s.twoCol}><section className={s.card}><div className={s.cardTitle}><h3>Execution receipt</h3><Badge tone="success">Status 1</Badge></div><Hash label="Transaction hash / LOCAL" value={execution.transactionHash}/><Hash label="Intent hash" value={execution.intentHash}/><div className={s.checkRow}><span>Block</span><strong>{execution.blockNumber}</strong></div><div className={s.checkRow}><span>Gas used</span><strong>{Number(execution.gasUsed).toLocaleString()}</strong></div><div className={s.checkRow}><span>Router allowance after swap</span><strong>{execution.remainingAllowance}</strong></div><div className={s.checkRow}><span>Evidence digest match</span><Badge tone="success">Verified</Badge></div></section><section className={s.card}><h3>Signed scope → observed result</h3><div className={s.guardList}>{['Caller is the delegated agent','Input is within the 10 tUSDC cap','Tokens and router are policy-bound','Recipient is the vault','Output meets the signed minimum','Receipt commits the evidence hash'].map(item=><div key={item}><Icon name="check" size={16}/>{item}</div>)}</div><p className={s.note}>The local fixture proves contract constraints. It does not prove LFJ liquidity, public-chain execution or trading profitability.</p></section></div>
          </>:null}
          <section className={`${s.card} ${attack?s.safetyPassed:s.safetyTest}`}><div className={s.cardTitle}><div><div className={s.eyebrow}>LOCAL NEGATIVE TEST / POSITIVE SAFETY RESULT</div><h3>{attack?'500 tUSDC attempted. 0 tUSDC moved.':'Local safety harness: exceed the delegated budget.'}</h3></div>{attack?<Badge tone="success">Boundary held</Badge>:<Badge tone="warning">Separate local test</Badge>}</div><div className={s.attackGrid}><div><span>Requested</span><strong>500 <small>tUSDC</small></strong></div><i>≠</i><div><span>Signed cap</span><strong>10 <small>tUSDC</small></strong></div><div className={s.attackResult}>{attack?<><Icon name="shield" size={28}/><div><strong>SingleTradeCap</strong><span>Contract rejected the transaction.</span></div></>:execution?button('attack','execution','Test over-budget request',true):<span>Run the isolated local policy flow to reproduce this negative test.</span>}</div></div>{attack?<><Hash label="Actual reverted LOCAL transaction" value={attack.transactionHash}/><div className={s.chartChecks}><span><Icon name="check" size={15}/>Token balances unchanged</span><span><Icon name="check" size={15}/>Execution nonce unchanged</span><span>Receipt status 0 · expected rejection</span></div></>:<p className={s.note}>The public Fuji transaction above is the positive execution proof. This separate local chain intentionally exercises the rejection path without wasting testnet funds.</p>}</section><div className={s.footerAction}>{execution&&!review?button('review','review','Build separate review plan'):review?<button className={s.primary} onClick={()=>setPanel('review')}>View review workflow <Icon name="arrow"/></button>:<button className={s.primary} onClick={()=>setPanel('evidence')}>Inspect public evidence <Icon name="arrow"/></button>}</div>
        </>)}

        {panel==='review'&&(!review?<section className={s.card}><Empty title="Review starts from an execution, not a claim.">The review plan binds the strategy version, policy digest, replay and execution receipt. The review agent is configured separately.</Empty>{execution?<div className={s.centerAction}>{button('review','review','Build separate review plan')}</div>:null}</section>:<>
          <section className={s.card}><div className={s.cardTitle}><div><h3>Execution → reflection</h3><p>AVAX Trend v1 · independent review workflow</p></div><Badge tone="brandTone">Plan ready / not scheduled</Badge></div><div className={s.reviewFlow}><div className={s.triggerNode}><Icon name="play"/><strong>Confirmed execution</strong><span>Event trigger / daily fallback</span></div><i>→</i><div><small>SCRIPT</small><strong>Collect evidence</strong><span>Replay + receipt + policy</span><Badge tone="success">Completed</Badge></div><i>→</i><div className={s.awaiting}><small>AGENT</small><strong>Propose a revision</strong><span>Strategy-aware review context</span><Badge tone="warning">Model not configured</Badge></div></div><p className={s.note}>The plan is generated; its scheduler and review-agent execution have not been started. No model output is fabricated.</p></section>
          <div className={s.twoCol}><section className={s.card}><h3>Evidence-led findings</h3><div className={s.findings}>{review.findings.map((f:string,i:number)=><div key={f}><span>{String(i+1).padStart(2,'0')}</span><p>{f}</p></div>)}</div><p className={s.note}>Deterministic summary from this run—not an LLM-generated analysis.</p></section><section className={s.card}><div className={s.cardTitle}><h3>Candidate next experiment</h3><Badge tone="warning">Draft / not promoted</Badge></div><p className={s.proposal}>{review.proposal.suggestion}</p><div className={s.guardList}>{['A new backtest is required','Operator reviews the proposed revision','Strategy changes require a new signed policy','The agent cannot expand its own budget'].map(item=><div key={item}><Icon name="shield" size={16}/>{item}</div>)}</div></section></div><div className={s.footerAction}><button className={s.primary} onClick={()=>setPanel('evidence')}>Inspect the complete evidence <Icon name="arrow"/></button></div>
        </>)}

        {panel==='evidence'&&<>
          <div className={s.twoCol}><section className={s.card}><div className={s.cardTitle}><h3>Evidence commitment</h3><Badge tone={fujiExecution?.status==='confirmed'||execution?.evidenceVerified?'success':'muted'}>{fujiExecution?.status==='confirmed'?'Committed on Fuji':execution?.evidenceVerified?'Digest verified':'Pending execution'}</Badge></div><Hash label="Bundle digest" value={fujiExecution?.executionEvidence?.evidenceHash||state?.evidence?.hash}/><Hash label="Fuji policy digest" value={fujiExecution?.policy?.policyHash}/><Hash label="Fuji execution event commitment" value={fujiExecution?.executionEvidence?.evidenceHash}/><Hash label="Public transaction" value={fujiExecution?.executionEvidence?.transactionHash}/><div className={s.callout}><strong>Integrity is not truth.</strong><p>A matching hash demonstrates that the recorded execution commits to the same evidence digest. It does not prove the research is correct or the strategy will make money.</p></div></section><section className={s.card}><h3>Verification ledger</h3>{[['Public market data',m?'Captured':'Not run'],['Nerya historical replay',bt?'Completed':'Not run'],['Fuji / LFJ reads',state?.fuji?.status==='verified'?'Verified':'Not verified'],['Fuji PolicyVault execution',fujiExecution?.status==='confirmed'?'Confirmed':'Not broadcast'],['Local oversized-order rejection',attack?'Verified':'Not run'],['LLM / multi-agent execution','Not invoked'],['Contract security audit','Not audited']].map(([label,value])=><div className={s.checkRow} key={label}><span>{label}</span><strong className={['Not broadcast','Not invoked','Not audited','Not verified'].includes(value)?s.warningText:''}>{value}</strong></div>)}</section></div>
          <section className={s.card}><div className={s.cardTitle}><h3>Run journal</h3><span className={s.note}>Hash-linked local event log</span></div><div className={s.journal}>{state?.events?.map((e:Row)=><div key={e.sequence}><span className={s.eventNumber}>{String(e.sequence).padStart(2,'0')}</span><span className={s.eventDot}/><div><strong>{e.kind.replaceAll('.',' / ')}</strong><code>{short(e.hash)}</code></div><time>{new Date(e.time).toLocaleTimeString('en-GB',{timeZone:'UTC'})} UTC</time></div>)}</div></section><div className={s.footerAction}><button className={s.secondary} onClick={()=>setShowRaw(!showRaw)}>{showRaw?'Hide raw evidence':'Inspect raw evidence'}</button><button className={s.primary} onClick={()=>void download()}>Export full bundle <Icon name="file"/></button></div>{showRaw?<pre className={s.raw}>{JSON.stringify({evidence:state?.evidence,policy:p,execution,attack,review},null,2)}</pre>:null}
        </>}
        <footer className={s.footer}><span><span className={s.footerDot}/> Nerya competition workspace</span><span>AI proposes. Policy constrains. Evidence remains.</span><code>{state?.runId?.slice(0,19)||'Connecting…'}</code></footer>
      </div>
    </div>
  </div>;
}
