/** Browser-side fixture for the isolated :18381 review server only.
 * Data must be the JSON generated by the Research Skill publisher.
 * Does not bypass or alter the production login, API, Agent, or workspace.
 */
module.exports = function installResearchFixture(fixture) {
  if (location.origin !== 'http://127.0.0.1:18381' || window.top !== window) return;
  localStorage.setItem('nerya.ui_settings.v1', JSON.stringify({ language: 'zh', darkMode: 'dark' }));
  window.__researchErrors = [];
  window.__researchRequests = [];
  window.addEventListener('error', event => window.__researchErrors.push(event.message));
  window.addEventListener('unhandledrejection', event => window.__researchErrors.push(String(event.reason)));
  const originalFetch = window.fetch.bind(window);
  const session = 'research-visual-acceptance';
  const title = 'BTC / ETH 投研与资金流分析 · UI 验收';
  const report = '## 研究图表已发布\n\n本页使用明确标记的合成测试数据，验证研究交付的完整展示链路，不代表真实行情或新闻。\n\n已发布 BTC / ETH 两个研究品种、两张 K 线和两张高级研究图表。\n\n点击底部品种查看 K 线、指标与相关资讯；左侧「研究图表」可对比资金流与归一化趋势。';
  const meta = id => ({ id, session_id: id, title: id === session ? title : '独立空白会话 · 验收', created_at: fixture.stamp, updated_at: fixture.stamp, message_count: id === session ? 2 : 0 });
  window.fetch = async (input, options = {}) => {
    const url = new URL(typeof input === 'string' ? input : input.url || String(input), location.href);
    if (url.origin !== location.origin || !url.pathname.startsWith('/api/')) return originalFetch(input, options);
    const path = url.pathname.replace(/^\/api\/proxy/, '');
    const body = typeof options.body === 'string' ? JSON.parse(options.body) : {};
    const id = url.searchParams.get('session_id') || session;
    window.__researchRequests.push({ path, body });
    let value = { ok: true, items: [], count: 0, total: 0, events: [], approvals: [] };
    if (path === '/auth/status') value = { ok: true, local_access: true, authenticated: true, password_configured: true };
    else if (path === '/agent/sessions') value = { sessions: [meta(session), meta('research-empty-acceptance')], has_more: false };
    else if (path === '/agent/session') value = { ...meta(id), messages: [] };
    else if (path === '/agent/session/transcript') value = { ok: true, ...meta(id), messages: id === session ? [
      { message_id: 'research-query', role: 'user', content: title, ts: fixture.stamp },
      { message_id: 'research-answer', role: 'assistant', content: report, ts: fixture.stamp, turn: { turn_id: 'research-fixture-turn', reply_text: report, blocks: [
        { block: { kind: 'tool_use', action: 'script_run', skill_id: 'research', call_id: 'publish-research', payload: { skill_id: 'research', name: 'publish_visuals.py', args: ['--input', 'TEST-FIXTURE.json'] } } },
        { block: { kind: 'tool_result', action: 'script_run', skill_id: 'research', call_id: 'publish-research', ok: true, result: fixture.native_result || fixture.result } },
        ...(fixture.native_result ? [] : fixture.blocks).map(block => ({ block })),
      ] } },
    ] : [], count: id === session ? 2 : 0 };
    else if (path === '/agent/stream/events') value = { events: [], latest_seq: 0, cursor: 0, count: 0 };
    else if (path === '/teams/agents') value = { ok: true, agents: [] };
    else if (path === '/charts/get') value = fixture.artifacts[url.searchParams.get('id')] ? { ok: true, payload: fixture.artifacts[url.searchParams.get('id')] } : { ok: false, error: 'fixture_not_found' };
    else if (path === '/market/news') value = { ok: !window.__researchNewsFailure, items: fixture.result.research_context.instruments.flatMap(row => row.news), fetched_at: Date.parse(fixture.stamp) / 1000 };
    else if (path === '/market/candles') {
      const symbol = String(body.market || 'BTC').includes('ETH') ? 'ETH' : 'BTC';
      const block = fixture.blocks.find(row => row.instrument?.market.includes(symbol));
      value = { market: block.instrument.market, venue: 'binance', interval: body.interval || '1h', candles: fixture.artifacts[block.chart_id].series[0].data.map(row => ({ ts: row.time, open: row.open, high: row.high, low: row.low, close: row.close, volume: row.volume })), _envelope: { mode: 'mock', source: 'TEST FIXTURE' } };
    } else if (path === '/workspace') value = { root: 'TEST FIXTURE · UI 验收', live_trading_enabled: false, kill_switch: false };
    else if (path === '/health') value = { status: 'ok' };
    else if (path === '/setup/readiness') value = { status: 'ok', data: { checks: [], blocking: [] } };
    else if (path === '/operator/nav') value = { ok: true, primary: [], advanced: [], data: { primary: [], advanced: [] } };
    else if (path === '/operator/overview') value = { status: 'ok', data: { attention: [], counts: {}, accounts: [], strategies: [] } };
    else if (path === '/llm/config') value = { ok: true, tiers: [], provider_profiles: [], default_tier: 'medium', reasoning_levels: ['none'] };
    else if (path === '/llm/providers' || path === '/llm/catalog') value = { providers: [] };
    else if (path === '/llm/tiers') value = { tiers: [], count: 0 };
    else if (path === '/market/venues') value = { venues: [] };
    else if (path === '/accounts/list') value = { accounts: [], ts: 0 };
    else if (path.includes('strategy/list')) value = { ok: true, strategies: [] };
    return new Response(JSON.stringify(value), { status: 200, headers: { 'content-type': 'application/json' } });
  };
};
