"""nerya.strategies — Agent-generated strategy runtime.

Implements the 7 plan in

A strategy is an *agent-generated package* under
``workspace/strategies/<strategy_id>/`` containing:

* ``strategy.yml`` — typed manifest (markets, accounts, schedule, policy,
  optional tuning block, llm policy, subagents).
* ``strategy.md`` — operator-readable playbook / intent.
* ``main.py`` — the entrypoint imported by :class:`StrategyRunner`. It
  exposes ``run(ctx: StrategyContext) -> StrategyResult``.
* ``subagents/<name>.agent.md`` — strategy-scoped subagent prompts.
* ``runs/<run_id>.json`` / ``state/state.json`` / ``versions/<hash>.json``
  — per-run artifacts written by the runner.

Generated code only sees the :class:`StrategyContext` facade — no raw
``Config``, vault, signer, connector, or ``SkillKernel``. Every order
goes through ``ctx.trading.submit_intent`` which still passes through
the existing risk-gated trading kernel.

Public surface:

* :class:`StrategyManifest` / :class:`StrategyPackage` — typed loaders.
* :class:`StrategyContext` / :class:`StrategyResult` — runtime facade.
* :class:`StrategyRunner` — single-tick executor.
"""

from __future__ import annotations

from .package import (
    StrategyAgentProfile,
    StrategyAgentSessionConfig,
    StrategyLLMPolicy,
    StrategyManifest,
    StrategyPackage,
    StrategyPolicy,
    StrategySchedule,
    StrategyTuningConfig,
    load_package,
    load_packages,
)
from .agent_task import StrategyAgentTask
from .prompt_io import StrategyPromptIO
from .result import ResultBuilder, StrategyResult, StrategyResultStatus
from .context import (
    StrategyAudit,
    StrategyClock,
    StrategyConfig,
    StrategyContext,
    StrategyDedupe,
    StrategyLLMFacade,
    StrategyMarket,
    StrategyMessages,
    StrategyNews,
    StrategyPnL,
    StrategyPortfolio,
    StrategyPosition,
    StrategyPolicyView,
    StrategyRuntimeError,
    StrategyState,
    StrategySubAgents,
    StrategyTrading,
    StrategyTriggerContext,
    build_strategy_context,
)
from .state import (
    KillSwitchState,
    StrategyKillSwitch,
    StrategyRunRecord,
    StrategyRunStore,
    StrategyVersionRecord,
    StrategyVersionRegistry,
    new_run_id,
)
from .runner import (
    StrategyRunInputs,
    StrategyRunOutputs,
    StrategyRunner,
    StrategyTimeoutError,
)
from .performance import StrategyPerformanceSnapshot, build_snapshot
from .evolution import StrategyEvolutionRunner, TuningRunResult

# ---------------------------------------------------------------------------
# Framework-compat lazy surface (PEP 562)
# ---------------------------------------------------------------------------
# The compat layer (Freqtrade / VNpy adapters) pulls in the validator via
# the importer, and the validator imports sibling modules — importing it
# eagerly here would re-enter a partially-initialised package (the same
# cycle the runner's lazy import in nerya.tools works around). Strategies
# generated by the compat importer do ``from nerya.strategies import
# run_compat_tick`` at runtime, which resolves through ``__getattr__``
# below once the package is fully loaded.

_LAZY_COMPAT_ATTRS: dict[str, tuple[str, str]] = {
    "run_compat_tick": ("nerya.strategies.compat.entrypoint", "run_compat_tick"),
    "load_framework_strategy": (
        "nerya.strategies.compat.entrypoint",
        "load_framework_strategy",
    ),
    "CompatRunError": ("nerya.strategies.compat.entrypoint", "CompatRunError"),
    "import_external_strategy": (
        "nerya.strategies.compat.importer",
        "import_external_strategy",
    ),
    "ImportExternalResult": ("nerya.strategies.compat.importer", "ImportExternalResult"),
    "detect_framework": ("nerya.strategies.compat.detect", "detect_framework"),
    "detect_frameworks": ("nerya.strategies.compat.detect", "detect_frameworks"),
    "FrameworkInfo": ("nerya.strategies.compat.detect", "FrameworkInfo"),
}

# Extend __all__ so introspection matches the lazy surface.
__all__ = [
    "KillSwitchState",
    "ResultBuilder",
    "StrategyAudit",
    "StrategyAgentProfile",
    "StrategyAgentSessionConfig",
    "StrategyAgentTask",
    "StrategyClock",
    "StrategyConfig",
    "StrategyContext",
    "StrategyDedupe",
    "StrategyEvolutionRunner",
    "StrategyKillSwitch",
    "StrategyLLMFacade",
    "StrategyLLMPolicy",
    "StrategyManifest",
    "StrategyMarket",
    "StrategyMessages",
    "StrategyNews",
    "StrategyPnL",
    "StrategyPackage",
    "StrategyPerformanceSnapshot",
    "StrategyPortfolio",
    "StrategyPosition",
    "StrategyPromptIO",
    "StrategyPolicy",
    "StrategyPolicyView",
    "StrategyResult",
    "StrategyResultStatus",
    "StrategyRunInputs",
    "StrategyRunOutputs",
    "StrategyRunRecord",
    "StrategyRunStore",
    "StrategyRunner",
    "StrategyRuntimeError",
    "StrategySchedule",
    "StrategyState",
    "StrategySubAgents",
    "StrategyTimeoutError",
    "StrategyTrading",
    "StrategyTriggerContext",
    "StrategyTuningConfig",
    "StrategyVersionRecord",
    "StrategyVersionRegistry",
    "TuningRunResult",
    "build_snapshot",
    "build_strategy_context",
    "load_package",
    "load_packages",
    "new_run_id",
    # lazy framework-compat surface
    "run_compat_tick",
    "load_framework_strategy",
    "CompatRunError",
    "import_external_strategy",
    "ImportExternalResult",
    "detect_framework",
    "detect_frameworks",
    "FrameworkInfo",
]


def __getattr__(name: str):  # noqa: ANN202 — PEP 562 signature
    lazy = _LAZY_COMPAT_ATTRS.get(name)
    if lazy is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    import importlib

    module_name, attr = lazy
    value = getattr(importlib.import_module(module_name), attr)
    globals()[name] = value  # cache — subsequent lookups skip the hook
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LAZY_COMPAT_ATTRS))
