"""Translate upstream slash-commands into Nerya trigger routes.

Upstream shape (``financial-services/plugins/vertical-plugins/<v>/commands/<name>.md``)::

    ---
    description: Draft an investment committee memo
    argument-hint: "[company name]"
    ---

    Load the `ic-memo` skill and draft a structured IC memo …

These are *thin loaders* — three lines of frontmatter plus one English
sentence telling the agent which skill to load.

Nerya does not have slash commands; it has :mod:`nerya.triggers.routes`.
A user typing the equivalent of ``/ic-memo`` would emit a
:class:`~nerya.triggers.user_command.TriggerEvent` with
``kind="user.command"`` and ``payload.command="finance.private_equity.ic_memo"``.
The route table maps that event to a target — typically ``main`` (so the
main agent picks the skill itself, exactly the way Nerya already routes
``news_alpha_to_main``).

We deliberately *do not* hard-route to ``skill:<id>.run``: upstream skills
have no ``actions`` (see ``nerya/skills/manifest.py::SkillManifest._build``
— ``actions == {}`` for every ``SKILL.md``-loaded skill), so there is no
runtime-callable target. Routing to ``main`` lets the agent loop
naturally pick up the SKILL.md playbook the way it does for any other
imported skill.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from .name_map import SkillTarget, to_snake

#: Frontmatter regex for the upstream command files. Matches the same
#: ``--- … ---`` envelope Nerya itself uses; we keep the regex local so
#: the importer has no runtime dependency on Nerya internals.
_FRONTMATTER_RE = re.compile(
    r"\A---\s*\n(?P<fm>.*?)\n---\s*\n(?P<body>.*)",
    re.DOTALL,
)

#: Loose regex that pulls ``description:`` and ``argument-hint:`` out of
#: a frontmatter block. We do not import a YAML library — these files
#: are simple enough that a key-value scan is robust and zero-dependency.
_KV_RE = re.compile(r"^(?P<key>[a-zA-Z][\w-]*)\s*:\s*(?P<value>.+?)\s*$", re.MULTILINE)


@dataclass(frozen=True)
class CommandRoute:
    """One imported slash-command, ready to be serialised into routes.yml."""

    upstream_command_md: Path
    upstream_command_token: str    # ``ic-memo``
    nerya_command_token: str       # ``ic_memo``
    namespace_id: str              # ``finance.private_equity.ic_memo``
    description: str
    argument_hint: str
    skill_target: SkillTarget

    @property
    def route_id(self) -> str:
        """Stable id for the routes.yml entry (must be unique workspace-wide)."""
        return f"finance_cmd_{self.skill_target.nerya_vertical}_{self.nerya_command_token}"


def parse_command_md(text: str) -> tuple[str, str, str]:
    """Return ``(description, argument_hint, body)`` from an upstream command file."""
    match = _FRONTMATTER_RE.match(text)
    if not match:
        return ("", "", text.strip())
    fm = match.group("fm")
    body = match.group("body").strip()
    description = ""
    argument_hint = ""
    for kv in _KV_RE.finditer(fm):
        key = kv.group("key").lower()
        value = kv.group("value").strip().strip('"').strip("'")
        if key == "description":
            description = value
        elif key in ("argument-hint", "argument_hint"):
            argument_hint = value
    return description, argument_hint, body


def derive_route(
    *,
    upstream_command_md: Path,
    skill_target: SkillTarget,
) -> CommandRoute:
    """Build a :class:`CommandRoute` from one upstream ``commands/<name>.md``."""
    upstream_token = upstream_command_md.stem
    description, argument_hint, _body = parse_command_md(
        upstream_command_md.read_text(encoding="utf-8")
    )
    nerya_token = to_snake(upstream_token)
    namespace_id = (
        f"finance.{skill_target.nerya_vertical}.{nerya_token}"
        if nerya_token != skill_target.skill_id
        else skill_target.namespace_id
    )
    return CommandRoute(
        upstream_command_md=upstream_command_md,
        upstream_command_token=upstream_token,
        nerya_command_token=nerya_token,
        namespace_id=namespace_id,
        description=description,
        argument_hint=argument_hint,
        skill_target=skill_target,
    )


def render_routes_yml(routes: list[CommandRoute]) -> str:
    """Render routes as a stand-alone YAML document.

    The output is intentionally hand-rolled (no PyYAML dependency at
    runtime). It is meant to be merged into the operator's existing
    ``triggers/routes.yml`` by a future ``cli upgrade-routes`` step;
    Phase A only writes a side-car file at
    ``workspace/triggers/finance.routes.yml`` so the operator can
    review-and-merge.
    """
    lines: list[str] = [
        "# finance.routes.yml — generated by finance_skills_importer.",
        "# Imported slash-commands route to ``main`` so the agent loop can",
        "# load the corresponding SKILL.md playbook. No skill action is",
        "# directly invoked because imported financial-services skills",
        "# carry no executable ``actions`` (frontmatter-only skills).",
        "version: 1",
        "routes:",
    ]
    for route in routes:
        lines.extend(_render_route(route))
    lines.append("")
    return "\n".join(lines)


def _render_route(route: CommandRoute) -> list[str]:
    description = route.description.replace('"', '\\"')
    argument_hint = route.argument_hint.replace('"', '\\"')
    return [
        f"  - id: {route.route_id}",
        f'    description: "{description}"',
        "    match:",
        '      kind: user.command',
        f"      payload.command: {route.namespace_id}",
        '    target: main',
        "    enabled: true",
        "    cooldown_seconds: 0",
        "    extra:",
        f"      finance_skill: {route.skill_target.namespace_id}",
        f"      argument_hint: \"{argument_hint}\"",
        f"      upstream_token: {route.upstream_command_token}",
    ]


__all__ = [
    "CommandRoute",
    "derive_route",
    "parse_command_md",
    "render_routes_yml",
]
