"""Scaffold a new skill — either as a proposal or as a real runnable skill.

Audit 4.6 / 6.2: the original generator emitted only
``proposal_only_unimplemented`` scaffolds, which the runtime refuses to
dispatch. That made "Agent authors a new skill" a dead-end flow — the
operator still had to hand-write everything.

This module now ships two entry points:

* :func:`propose_skill`  — legacy, unchanged: produces a proposal-only
  scaffold. Dispatch remains blocked until the operator edits the body
  and drops the status flag. Useful for "please review this idea" flows.
* :func:`scaffold_skill` — new, real scaffold: stages a *runnable* skill
  under ``workspace/skills/pending/<skill_id>/`` that actually executes
  once promoted via ``promote_installed``. The default action echoes its
  payload so operators can verify end-to-end dispatch before flashing in
  a real implementation.
"""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from ..core import jsonl, yaml_io
from ..core.errors import SkillActionError
from ..core.paths import WorkspacePaths
from ..core.time import now_iso
from .patch_proposal import Proposal, create_proposal


# The ``status`` key is part of the truth gate: the skill registry refuses to
# dispatch a skill whose status is ``proposal_only_unimplemented``.
SKELETON_MANIFEST = {
    "id": "generated_skill",
    "version": "0.1.0",
    "title": "Generated Skill",
    "description": (
        "Generated by evolution. Proposal-only — an operator must review, "
        "flesh out, and accept before runtime can dispatch it."
    ),
    "source": "generated",
    "status": "proposal_only_unimplemented",
    "permissions": [],
    "actions": [{
        "name": "placeholder",
        "permissions": [],
        "risk_gate": "n/a",
        "input_schema": {"type": "object"},
        "output_schema": {"type": "object"},
        "status": "proposal_only_unimplemented",
    }],
}

def _render_skill_md(manifest: dict[str, Any], *, body: str = "") -> str:
    """Render a SKILL.md file with the manifest baked into YAML frontmatter.

    skill-runtime compatibility: ``SKILL.md`` (with frontmatter) is the
    *only* manifest format. Evolution scaffolds previously emitted a
    sidecar ``skill.yml`` plus a stub ``SKILL.md``; that drift has been
    removed.
    """
    raw = yaml_io.dumps(manifest).rstrip()
    fm = f"---\n{raw}\n---\n"
    body = body.rstrip()
    return f"{fm}\n{body}\n" if body else fm


SKELETON_ACTIONS = (
    '"""Proposal-only generated skill scaffold.\n\n'
    'Nerya refuses to dispatch actions tagged ``proposal_only_unimplemented``\n'
    'at runtime. The operator must replace this body with a real action and\n'
    'drop the status flag before the skill can run.\n"""\n'
    "from nerya.core.errors import SkillActionError\n"
    "\n"
    "def placeholder(ctx, **payload):\n"
    '    raise SkillActionError(\n'
    '        "generated placeholder skill is proposal_only_unimplemented; "\n'
    '        "operator must implement and remove the status flag"\n'
    '    )\n'
)


def propose_skill(paths: WorkspacePaths, *, skill_id: str, summary: str,
                  manifest: dict[str, Any] | None = None,
                  actions_py: str | None = None) -> Proposal:
    manifest = manifest or {**SKELETON_MANIFEST, "id": skill_id, "title": skill_id}
    manifest["id"] = skill_id
    # Never let the caller pass a manifest without the proposal-only marker.
    manifest.setdefault("status", "proposal_only_unimplemented")
    return create_proposal(
        paths, kind="skill_proposal", summary=summary,
        rationale=(
            f"# Skill proposal {skill_id}\n\n{summary}\n\n"
            f"Status: proposal_only_unimplemented. Operator must replace the "
            f"placeholder action body and drop the status flag before the "
            f"skill can be dispatched.\n"
        ),
        extra_files={
            f"new_skill/{skill_id}/SKILL.md": _render_skill_md(
                manifest, body=(
                    f"# {skill_id}\n\nStatus: proposal_only_unimplemented.\n\n"
                    f"{summary}\n"
                ),
            ),
            f"new_skill/{skill_id}/actions.py": actions_py or SKELETON_ACTIONS,
            f"new_skill/{skill_id}/README.md": (
                f"# {skill_id}\n\nStatus: proposal_only_unimplemented.\n\n"
                f"{summary}\n"
            ),
        },
    )


# ======================================================================
# Audit 4.6 — real runnable scaffold
# ======================================================================

_SKILL_ID_OK = re.compile(r"^[a-z][a-z0-9_]{1,60}$")


def _runnable_manifest(skill_id: str, *, title: str, summary: str,
                       actions: list[dict[str, Any]]) -> dict[str, Any]:
    """Build a runnable manifest (NO ``proposal_only_unimplemented``).

    A scaffold skill is intentionally dispatch-enabled once promoted —
    the operator gets a working echo action they can flesh out, not a
    dead-end stub that blocks the runtime.
    """
    return {
        "id": skill_id,
        "version": "0.1.0",
        "title": title or skill_id,
        "description": summary,
        "source": "generated_scaffold",
        "permissions": [],
        "actions": actions or [{
            "name": "ping",
            "permissions": [],
            "risk_gate": "n/a",
            "description": (
                "Echoes the input payload for scaffold-smoke-testing. "
                "Operator replaces this with the real implementation."
            ),
            "input_schema": {"type": "object"},
            "output_schema": {"type": "object"},
        }],
    }


_RUNNABLE_ACTIONS_PY = (
    '"""Scaffolded skill — runnable out of the box.\n\n'
    'Generated by :func:`nerya.evolution.skill_generator.scaffold_skill`.\n'
    'Replace the ``ping`` body with the real implementation; the runtime\n'
    'will happily dispatch it once promoted to ``skills/installed``.\n"""\n'
    "from __future__ import annotations\n"
    "\n"
    "from typing import Any\n"
    "\n"
    "\n"
    "def ping(ctx, **payload: Any) -> dict[str, Any]:\n"
    '    """Echo the payload so dispatchers can verify end-to-end wiring."""\n'
    "    return {\n"
    '        "ok": True,\n'
    '        "skill_id": ctx.manifest.id,\n'
    '        "echo": payload,\n'
    "    }\n"
)


@dataclass
class ScaffoldReport:
    """Result of :func:`scaffold_skill`.

    Intentionally mirrors :class:`InstallReport` so dashboards and CLI
    tooling can treat scaffolded + installed skills the same way.
    """
    skill_id: str
    title: str
    summary: str
    files: list[str] = field(default_factory=list)
    staged_at: Path | None = None
    proposal_id: str | None = None
    runnable: bool = True

    def asdict(self) -> dict[str, Any]:
        return {
            **asdict(self),
            "staged_at": None if self.staged_at is None else str(self.staged_at),
        }


def scaffold_skill(paths: WorkspacePaths, *, skill_id: str, summary: str,
                   title: str | None = None,
                   manifest: dict[str, Any] | None = None,
                   actions_py: str | None = None,
                   actions: list[dict[str, Any]] | None = None,
                   create_proposal_record: bool = True,
                   ) -> ScaffoldReport:
    """Stage a real, runnable scaffold under ``skills/pending/<skill_id>/``.

    The scaffold:

    * writes ``skill.yml`` + ``actions.py`` + ``README.md`` to
      ``workspace/skills/pending/<skill_id>/``;
    * does **not** tag the manifest ``proposal_only_unimplemented`` — the
      dispatcher accepts the skill once promoted via
      :func:`nerya.skills.installer.promote_installed`;
    * optionally emits a proposal record so the operator UI can show the
      scaffold in the normal approval queue (``create_proposal_record``
      defaults to ``True``).

    :raises SkillActionError: if ``skill_id`` is invalid or the pending
        directory already exists (the caller must remove or promote the
        prior scaffold first).
    """
    skill_id = (skill_id or "").strip().lower()
    if not _SKILL_ID_OK.match(skill_id):
        raise SkillActionError(
            f"invalid skill_id {skill_id!r}; use snake_case a-z0-9_ "
            "starting with a letter"
        )
    if not summary.strip():
        raise SkillActionError("scaffold_skill requires a non-empty 'summary'")

    manifest_doc = manifest
    if manifest_doc is None:
        manifest_doc = _runnable_manifest(
            skill_id,
            title=title or skill_id,
            summary=summary,
            actions=actions or [],
        )
    manifest_doc["id"] = skill_id
    manifest_doc.setdefault("source", "generated_scaffold")
    # Explicitly refuse to ship a `proposal_only_unimplemented` scaffold
    # via this entry-point — that's what :func:`propose_skill` is for.
    if manifest_doc.get("status") == "proposal_only_unimplemented":
        raise SkillActionError(
            "scaffold_skill must produce a runnable skill; caller passed "
            "status='proposal_only_unimplemented' — use propose_skill instead"
        )

    staged = paths.skills_pending / skill_id
    if staged.exists():
        raise SkillActionError(
            f"pending scaffold already exists at {staged}; remove or "
            "promote it first before re-scaffolding"
        )
    staged.parent.mkdir(parents=True, exist_ok=True)
    staged.mkdir(parents=True)

    try:
        (staged / "SKILL.md").write_text(
            _render_skill_md(
                manifest_doc,
                body=(
                    f"# {manifest_doc.get('title') or skill_id}\n\n"
                    f"{summary}\n\n"
                    f"Status: runnable scaffold. Operator should replace the "
                    f"placeholder ``ping`` action with the real implementation "
                    f"and promote the skill via ``promote_installed`` to "
                    f"enable it in the registry.\n"
                ),
            ),
            encoding="utf-8",
        )
        (staged / "actions.py").write_text(
            actions_py or _RUNNABLE_ACTIONS_PY, encoding="utf-8",
        )
        (staged / "README.md").write_text(
            f"# {skill_id}\n\n{summary}\n\n"
            f"Status: runnable scaffold. Operator should replace the "
            f"placeholder ``ping`` action with the real implementation "
            f"and promote the skill via ``promote_installed`` to enable "
            f"it in the registry.\n",
            encoding="utf-8",
        )

        files = sorted(
            p.relative_to(staged).as_posix()
            for p in staged.rglob("*") if p.is_file()
        )
        report = ScaffoldReport(
            skill_id=skill_id,
            title=manifest_doc.get("title") or skill_id,
            summary=summary,
            files=files,
            staged_at=staged,
            runnable=True,
        )

        if create_proposal_record:
            prop = create_proposal(
                paths,
                kind="skill_scaffold",
                summary=f"Runnable scaffold for skill {skill_id}",
                rationale=(
                    f"# Skill scaffold `{skill_id}`\n\n"
                    f"{summary}\n\n"
                    "Status: runnable. This is NOT a proposal-only stub — "
                    "the scaffold dispatches once promoted to "
                    "`skills/installed`. Operator should still review the "
                    "action body and permission set before promotion.\n"
                ),
                extra_files={
                    "scaffold_report.json":
                        json.dumps(report.asdict(), indent=2),
                    "target.yml":
                        f"target: skills/installed/{skill_id}\n",
                },
            )
            report.proposal_id = prop.id

        (staged / "scaffold_report.json").write_text(
            json.dumps(report.asdict(), indent=2), encoding="utf-8",
        )

        jsonl.append(paths.journal("evolution"), {
            "kind": "skill_scaffold",
            "skill_id": skill_id,
            "staged": str(staged),
            "proposal_id": report.proposal_id,
            "runnable": True,
            "ts": now_iso(),
        })
        return report
    except Exception:
        # Roll back the staged directory so a half-written scaffold never
        # fools a later promotion.
        shutil.rmtree(staged, ignore_errors=True)
        raise


__all__ = [
    "SKELETON_MANIFEST",
    "SKELETON_ACTIONS",
    "ScaffoldReport",
    "propose_skill",
    "scaffold_skill",
]
