"""Local SearXNG container lifecycle helpers.

Provides a thin wrapper that:

- generates a minimal SearXNG ``settings.yml`` with ``formats: [html, json]``
  enabled (required by the :class:`SearXNGAdapter`),
- starts a Docker container bound to a configurable port,
- tracks pid / container-id state in
  ``<workspace>/state/searxng/state.json`` so the dashboard can render
  status across restarts,
- supports stop / status probes / config rotation.

The deployment is **opt-in** — nothing happens until the dashboard
explicitly calls ``deploy()``. We never auto-start a container.

Docker is the only supported runtime here. If the operator wants to run
SearXNG some other way (compose, k8s, hosted), they just type the URL
into the dashboard and we leave the deploy block alone.
"""

from __future__ import annotations

import json
import secrets
import shutil
import socket
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.error import URLError
from urllib.request import Request, urlopen


_DEFAULT_IMAGE = "searxng/searxng:latest"
_DEFAULT_CONTAINER = "nerya-searxng"
_DEFAULT_HOST_PORT = 8888
_PROBE_TIMEOUT_S = 4.0


@dataclass
class _Workspace:
    root: Path
    state_dir: Path
    config_dir: Path
    state_file: Path

    @classmethod
    def at(cls, workspace_root: Path | str) -> "_Workspace":
        root = Path(workspace_root)
        state_dir = root / "state" / "searxng"
        config_dir = root / "state" / "searxng" / "config"
        return cls(
            root=root,
            state_dir=state_dir,
            config_dir=config_dir,
            state_file=state_dir / "state.json",
        )


def _read_state(ws: _Workspace) -> dict[str, Any]:
    if not ws.state_file.exists():
        return {}
    try:
        return json.loads(ws.state_file.read_text(encoding="utf-8")) or {}
    except Exception:
        return {}


def _write_state(ws: _Workspace, data: dict[str, Any]) -> None:
    ws.state_dir.mkdir(parents=True, exist_ok=True)
    ws.state_file.write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def _docker_available() -> bool:
    return shutil.which("docker") is not None


def _docker_inspect(name: str) -> dict[str, Any]:
    try:
        res = subprocess.run(
            ["docker", "inspect", name],
            capture_output=True, text=True, timeout=10,
        )
    except Exception:
        return {}
    if res.returncode != 0 or not res.stdout.strip():
        return {}
    try:
        rows = json.loads(res.stdout)
    except Exception:
        return {}
    return rows[0] if isinstance(rows, list) and rows else {}


def _container_running(name: str) -> bool:
    info = _docker_inspect(name)
    state = (info.get("State") or {}) if isinstance(info, dict) else {}
    return bool(state.get("Running"))


def _http_probe(base_url: str, *, timeout_s: float = _PROBE_TIMEOUT_S) -> dict[str, Any]:
    base = base_url.rstrip("/")
    started = time.monotonic()
    try:
        req = Request(
            f"{base}/search?q=ping&format=json",
            headers={"Accept": "application/json", "User-Agent": "Nerya/probe"},
        )
        with urlopen(req, timeout=timeout_s) as resp:
            body = resp.read(2048)
            ct = resp.headers.get("Content-Type", "")
            elapsed = int((time.monotonic() - started) * 1000)
            return {
                "ok": True,
                "status": resp.status,
                "content_type": ct,
                "elapsed_ms": elapsed,
                "body_preview": body.decode("utf-8", errors="replace")[:200],
            }
    except URLError as exc:
        return {
            "ok": False,
            "elapsed_ms": int((time.monotonic() - started) * 1000),
            "error": f"URLError: {getattr(exc, 'reason', exc)}",
        }
    except socket.timeout:
        return {
            "ok": False,
            "elapsed_ms": int((time.monotonic() - started) * 1000),
            "error": "timeout",
        }
    except Exception as exc:  # noqa: BLE001
        return {
            "ok": False,
            "elapsed_ms": int((time.monotonic() - started) * 1000),
            "error": f"{type(exc).__name__}: {exc}",
        }


def _settings_yml(*, secret: str) -> str:
    return f"""# Auto-generated by Nerya — do not edit by hand.
use_default_settings: true

server:
  bind_address: "127.0.0.1"
  port: 8080
  secret_key: "{secret}"
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true

search:
  formats:
    - html
    - json
  safe_search: 0
  autocomplete: ""
  default_lang: "auto"
"""


def _ensure_config(ws: _Workspace) -> Path:
    ws.config_dir.mkdir(parents=True, exist_ok=True)
    settings_path = ws.config_dir / "settings.yml"
    if not settings_path.exists():
        secret = secrets.token_hex(32)
        settings_path.write_text(_settings_yml(secret=secret),
                                 encoding="utf-8")
    return settings_path


# ---------------------------------------------------------------------------
# Public surface
# ---------------------------------------------------------------------------


def status(workspace_root: Path | str, *, base_url: str = "") -> dict[str, Any]:
    ws = _Workspace.at(workspace_root)
    state = _read_state(ws)
    container_name = state.get("container_name") or _DEFAULT_CONTAINER
    has_docker = _docker_available()
    running = has_docker and _container_running(container_name)
    probe_url = (base_url or state.get("base_url")
                 or f"http://127.0.0.1:{state.get('host_port') or _DEFAULT_HOST_PORT}").rstrip("/")
    probe = _http_probe(probe_url) if probe_url else {"ok": False,
                                                       "error": "no probe url"}
    return {
        "ok": True,
        "docker_available": has_docker,
        "container_name": container_name,
        "container_running": running,
        "image": state.get("image") or _DEFAULT_IMAGE,
        "host_port": int(state.get("host_port") or _DEFAULT_HOST_PORT),
        "base_url": probe_url,
        "config_dir": str(ws.config_dir),
        "state_file": str(ws.state_file),
        "deployed": bool(state),
        "probe": probe,
    }


def deploy(
    workspace_root: Path | str,
    *,
    host_port: int | None = None,
    image: str | None = None,
    container_name: str | None = None,
    rebuild: bool = False,
) -> dict[str, Any]:
    ws = _Workspace.at(workspace_root)
    if not _docker_available():
        return {
            "ok": False,
            "error": "docker_unavailable",
            "detail": "docker CLI not on PATH; install Docker Desktop or use a remote SearXNG URL",
        }

    state = _read_state(ws)
    cname = container_name or state.get("container_name") or _DEFAULT_CONTAINER
    img = image or state.get("image") or _DEFAULT_IMAGE
    port = int(host_port or state.get("host_port") or _DEFAULT_HOST_PORT)
    base_url = f"http://127.0.0.1:{port}"

    settings_path = _ensure_config(ws)

    # If a container with this name exists, remove first when rebuilding.
    info = _docker_inspect(cname)
    exists = bool(info)
    if exists:
        if rebuild:
            subprocess.run(["docker", "rm", "-f", cname],
                           capture_output=True, text=True, timeout=20)
            exists = False
        else:
            running = _container_running(cname)
            if not running:
                # try to start it again
                start_res = subprocess.run(
                    ["docker", "start", cname],
                    capture_output=True, text=True, timeout=20,
                )
                if start_res.returncode != 0:
                    return {
                        "ok": False,
                        "error": "container_start_failed",
                        "detail": (start_res.stderr or start_res.stdout)[:1000],
                    }

    if not exists:
        # Pre-pull (best effort; ignore failure since `run` will pull too).
        subprocess.run(["docker", "pull", img],
                       capture_output=True, text=True, timeout=180)
        cmd = [
            "docker", "run", "-d",
            "--name", cname,
            "--restart", "unless-stopped",
            "-p", f"127.0.0.1:{port}:8080",
            "-v", f"{settings_path.parent}:/etc/searxng",
            "-e", "SEARXNG_BASE_URL=" + base_url + "/",
            img,
        ]
        run_res = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if run_res.returncode != 0:
            return {
                "ok": False,
                "error": "docker_run_failed",
                "detail": (run_res.stderr or run_res.stdout)[:2000],
            }

    # Persist state
    new_state = {
        "container_name": cname,
        "image": img,
        "host_port": port,
        "base_url": base_url,
        "deployed_at": int(time.time()),
        "settings_yml": str(settings_path),
    }
    _write_state(ws, new_state)

    # Wait briefly for the container to come up (up to ~10s).
    probe: dict[str, Any] = {"ok": False, "error": "not probed yet"}
    for _ in range(10):
        probe = _http_probe(base_url)
        if probe.get("ok"):
            break
        time.sleep(1.0)

    return {
        "ok": True,
        "container_name": cname,
        "image": img,
        "host_port": port,
        "base_url": base_url,
        "settings_yml": str(settings_path),
        "probe": probe,
    }


def teardown(workspace_root: Path | str, *,
             remove: bool = True) -> dict[str, Any]:
    ws = _Workspace.at(workspace_root)
    state = _read_state(ws)
    cname = state.get("container_name") or _DEFAULT_CONTAINER
    if not _docker_available():
        return {"ok": False, "error": "docker_unavailable"}
    info = _docker_inspect(cname)
    if not info:
        return {"ok": True, "removed": False, "running": False,
                "detail": "no container present"}
    cmd = ["docker", "rm", "-f", cname] if remove else ["docker", "stop", cname]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    if res.returncode != 0:
        return {
            "ok": False,
            "error": "docker_remove_failed" if remove else "docker_stop_failed",
            "detail": (res.stderr or res.stdout)[:1000],
        }
    if remove:
        # Keep config — operator may want to redeploy. State file just
        # carries whatever we last wrote; clearing it would destroy port
        # preference / image override silently.
        new_state = dict(state)
        new_state["torn_down_at"] = int(time.time())
        _write_state(ws, new_state)
    return {"ok": True, "removed": bool(remove), "running": False}


__all__ = ["status", "deploy", "teardown"]
